/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideSponsors: typeof import('./theme/components/AsideSponsors.vue')['default']
    'Bi:fileEarmarkWordFill': typeof import('~icons/bi/file-earmark-word-fill')['default']
    CardLink: typeof import('./theme/components/CardLink.vue')['default']
    Comment: typeof import('./theme/components/layout/Comment.vue')['default']
    Copyright: typeof import('./theme/components/Copyright.vue')['default']
    'EosIcons:modifiedDate': typeof import('~icons/eos-icons/modified-date')['default']
    Footer: typeof import('./theme/components/layout/Footer.vue')['default']
    MediumZoom: typeof import('./theme/components/MediumZoom.vue')['default']
    Mermaid: typeof import('./theme/components/Mermaid.vue')['default']
    'Octicon:feedPerson16': typeof import('~icons/octicon/feed-person16')['default']
    'Ooui:clock': typeof import('~icons/ooui/clock')['default']
    PageInfo: typeof import('./theme/components/layout/PageInfo.vue')['default']
    'RadixIcons:update': typeof import('~icons/radix-icons/update')['default']
  }
}
