/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideSponsors: typeof import('./.vitepress/theme/components/AsideSponsors.vue')['default']
    Copyright: typeof import('./.vitepress/theme/components/Copyright.vue')['default']
    Footer: typeof import('./.vitepress/theme/components/layout/Footer.vue')['default']
    MediumZoom: typeof import('./.vitepress/theme/components/MediumZoom.vue')['default']
  }
}
